#include "codegen/CMakeGenerator.hpp"

#include "utils/StringUtils.hpp"

namespace s2c::codegen {

std::string generateCMakeLists(const ir::Project& project, const std::string& executableName,
                               const std::vector<std::string>& sourceFiles) {
    std::string cm;
    cm += "# Generated by scratch2cpp from \"" + project.title + "\".\n";
    cm += "# Native CMake project: macOS, Windows, and Linux.\n";
    cm += "#\n";
    cm += "#   cmake -S . -B build\n";
    cm += "#   cmake --build build --config Release\n";
    cm += "#\n";
    cm += "# Unix:    ./build/" + executableName + "\n";
    cm += "# Windows: build\\Release\\" + executableName + ".exe   (Visual Studio)\n";
    cm += "#          build\\" + executableName + ".exe            (Ninja / NMake)\n";
    cm += "#\n";
    cm += "# SDL3 is located with find_package(SDL3). If it is not installed and\n";
    cm += "# SCRATCH_FETCH_SDL3 is ON (default), SDL3 is downloaded and built from source.\n";
    cm += "cmake_minimum_required(VERSION 3.21)\n";
    cm += "project(" + executableName + " LANGUAGES C CXX)\n\n";
    cm += "set(CMAKE_CXX_STANDARD 20)\n";
    cm += "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n";
    cm += "set(CMAKE_CXX_EXTENSIONS OFF)\n";
    cm += "if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)\n";
    cm += "    set(CMAKE_BUILD_TYPE Release CACHE STRING \"Build type\" FORCE)\n";
    cm += "endif()\n";
    cm += "if(WIN32)\n";
    cm += "    add_compile_definitions(NOMINMAX WIN32_LEAN_AND_MEAN)\n";
    cm += "endif()\n\n";
    cm += "option(SCRATCH_FETCH_SDL3 \"Download and build SDL3 when it is not installed\" ON)\n\n";
    cm += "find_package(SDL3 CONFIG QUIET)\n";
    cm += "if(NOT SDL3_FOUND)\n";
    cm += "    if(SCRATCH_FETCH_SDL3)\n";
    cm += "        message(STATUS \"SDL3 not found - fetching it from GitHub (set SCRATCH_FETCH_SDL3=OFF to disable)\")\n";
    cm += "        include(FetchContent)\n";
    cm += "        set(SDL_SHARED OFF CACHE BOOL \"\" FORCE)\n";
    cm += "        set(SDL_STATIC ON CACHE BOOL \"\" FORCE)\n";
    cm += "        set(SDL_TEST_LIBRARY OFF CACHE BOOL \"\" FORCE)\n";
    cm += "        FetchContent_Declare(SDL3\n";
    cm += "            GIT_REPOSITORY https://github.com/libsdl-org/SDL.git\n";
    cm += "            GIT_TAG release-3.2.20\n";
    cm += "            GIT_SHALLOW TRUE)\n";
    cm += "        FetchContent_MakeAvailable(SDL3)\n";
    cm += "    else()\n";
        cm += "        message(FATAL_ERROR \"SDL3 was not found. Install SDL3 (macOS: brew install sdl3; Windows: vcpkg install sdl3; Linux: apt install libsdl3-dev) or enable SCRATCH_FETCH_SDL3.\")\n";
    cm += "    endif()\n";
    cm += "endif()\n\n";
    cm += "# Scratch runtime (sprites, stage, scheduler, SDL3 rendering/input/audio).\n";
    cm += "add_subdirectory(runtime)\n\n";
    cm += "add_executable(" + executableName + "\n";
    for (const std::string& src : sourceFiles) cm += "    " + src + "\n";
    cm += ")\n";
    cm += "target_include_directories(" + executableName + " PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/include)\n";
    cm += "target_link_libraries(" + executableName + " PRIVATE scratch_runtime SDL3::SDL3)\n";
    cm += "# Assets are looked up next to the executable first, then in the source tree.\n";
    cm += "target_compile_definitions(" + executableName + " PRIVATE SCRATCH_ASSETS_DIR=\"${CMAKE_CURRENT_SOURCE_DIR}/assets\")\n";
    cm += "if(MSVC)\n";
    cm += "    target_compile_options(" + executableName + " PRIVATE /W3 /utf-8 /bigobj)\n";
    cm += "else()\n";
    cm += "    target_compile_options(" + executableName + " PRIVATE -Wall -Wno-unused-parameter -Wno-unused-variable -Wno-unused-but-set-variable)\n";
    cm += "endif()\n\n";
    cm += "# Copy assets next to the built executable so the binary can be run from anywhere.\n";
    cm += "# Quote paths: project titles may contain spaces or parentheses.\n";
    cm += "add_custom_command(TARGET " + executableName + " POST_BUILD\n";
    cm += "    COMMAND ${CMAKE_COMMAND} -E copy_directory\n";
    cm += "            \"${CMAKE_CURRENT_SOURCE_DIR}/assets\"\n";
    cm += "            \"$<TARGET_FILE_DIR:" + executableName + ">/assets\"\n";
    cm += "    COMMENT \"Copying Scratch assets\"\n";
    cm += "    VERBATIM)\n\n";
    cm += "# Copy the SDL3 shared library next to the executable on Windows.\n";
    cm += "if(WIN32 AND TARGET SDL3::SDL3-shared)\n";
    cm += "    add_custom_command(TARGET " + executableName + " POST_BUILD\n";
    cm += "        COMMAND ${CMAKE_COMMAND} -E copy_if_different\n";
    cm += "                \"$<TARGET_FILE:SDL3::SDL3-shared>\"\n";
    cm += "                \"$<TARGET_FILE_DIR:" + executableName + ">\"\n";
    cm += "        VERBATIM)\n";
    cm += "endif()\n";
    return cm;
}

std::string generateGitignore() {
    return "build/\nbuild-*/\n.cache/\n*.swp\n.DS_Store\n";
}

}  // namespace s2c::codegen
