#include "codegen/CppGenerator.hpp"

#include "codegen/Emitter.hpp"
#include "codegen/TargetCompiler.hpp"
#include "utils/Log.hpp"
#include "utils/StringUtils.hpp"

namespace s2c::codegen {

CppSources CppGenerator::generate() {
    CppSources out;
    out.executableName = str::sanitizeIdentifier(project_.title, "ScratchProject");

    const ProjectNames names = ProjectNames::build(project_);
    std::vector<std::string> classNames;
    for (const ir::Target& target : project_.targets) {
        log::detail("Generating " + (target.isStage ? std::string("stage") : "sprite \"" + target.name + "\""));
        TargetCompiler compiler(project_, target, names, diagnostics_);
        GeneratedTarget generated = compiler.generate();
        out.files["include/targets/" + generated.className + ".hpp"] = generated.header;
        const std::string source = "src/targets/" + generated.className + ".cpp";
        out.files[source] = generated.source;
        out.sourceFiles.push_back(source);
        classNames.push_back(generated.className);
    }

    out.files["include/Project.hpp"] = generateProjectHeader();
    out.files["src/Project.cpp"] = generateProjectSource(classNames);
    out.files["src/main.cpp"] = generateMain();
    out.sourceFiles.insert(out.sourceFiles.begin(), {"src/main.cpp", "src/Project.cpp"});
    return out;
}

std::string CppGenerator::generateProjectHeader() const {
    Emitter h;
    h.line("// Generated by scratch2cpp. Do not edit by hand.");
    h.line("#pragma once");
    h.line();
    h.line("#include \"scratch/Runtime.hpp\"");
    h.line();
    h.open("namespace project");
    h.line();
    h.line("// Window title, stage size and other runtime settings for this project.");
    h.line("scratch::RuntimeConfig config();");
    h.line();
    h.line("// Creates the stage and every sprite (in layer order) inside the runtime.");
    h.line("void registerTargets(scratch::Runtime& runtime);");
    h.line();
    h.close("  // namespace project");
    return h.str();
}

std::string CppGenerator::generateProjectSource(const std::vector<std::string>& classNames) const {
    Emitter s;
    s.line("// Generated by scratch2cpp from \"" + project_.title + "\". Do not edit by hand.");
    s.line("#include \"Project.hpp\"");
    s.line();
    for (const std::string& cls : classNames) s.line("#include \"targets/" + cls + ".hpp\"");
    s.line();
    s.open("namespace project");
    s.line();
    s.open("scratch::RuntimeConfig config()");
    s.line("scratch::RuntimeConfig cfg;");
    s.line("cfg.title = " + str::cppStringLiteral(project_.title) + ";");
    s.line("cfg.stageWidth = " + std::to_string(project_.stageWidth) + ";");
    s.line("cfg.stageHeight = " + std::to_string(project_.stageHeight) + ";");
    s.line("cfg.windowScale = " + std::to_string(windowScale_) + ";");
    s.line("cfg.fps = 30.0;   // Scratch runs at 30 frames per second");
    s.line("return cfg;");
    s.close();
    s.line();
    s.open("void registerTargets(scratch::Runtime& runtime)");
    for (size_t i = 0; i < project_.targets.size(); ++i) {
        const ir::Target& t = project_.targets[i];
        if (t.isStage) {
            s.line("runtime.createStage<" + classNames[i] + ">();");
        } else {
            s.line("runtime.createSprite<" + classNames[i] + ">();   // \"" + t.name + "\"");
        }
    }
    for (const ir::Monitor& mon : project_.monitors) {
        s.line("{");
        s.line("    scratch::Monitor m;");
        const bool isList = mon.opcode.find("list") != std::string::npos || !mon.listName.empty();
        s.line(std::string("    m.kind = scratch::Monitor::Kind::") + (isList ? "List;" : "Variable;"));
        std::string mode = "Default";
        if (mon.mode == "large") mode = "Large";
        else if (mon.mode == "slider") mode = "Slider";
        else if (mon.mode == "list") mode = "ListBox";
        s.line("    m.mode = scratch::Monitor::Mode::" + mode + ";");
        s.line("    m.name = " + str::cppStringLiteral(isList ? mon.listName : mon.variableName) + ";");
        s.line("    m.targetName = " + str::cppStringLiteral(mon.spriteName) + ";");
        s.line("    m.x = " + str::cppDoubleLiteral(mon.x) + ";");
        s.line("    m.y = " + str::cppDoubleLiteral(mon.y) + ";");
        s.line("    m.width = " + str::cppDoubleLiteral(mon.width) + ";");
        s.line("    m.height = " + str::cppDoubleLiteral(mon.height) + ";");
        s.line(std::string("    m.visible = ") + (mon.visible ? "true;" : "false;"));
        s.line("    m.sliderMin = " + str::cppDoubleLiteral(mon.sliderMin) + ";");
        s.line("    m.sliderMax = " + str::cppDoubleLiteral(mon.sliderMax) + ";");
        s.line(std::string("    m.discrete = ") + (mon.isDiscrete ? "true;" : "false;"));
        s.line("    runtime.addMonitor(std::move(m));");
        s.line("}");
    }
    s.close();
    s.line();
    s.close("  // namespace project");
    return s.str();
}

std::string CppGenerator::generateMain() const {
    Emitter m;
    m.line("// Generated by scratch2cpp. Entry point of the converted project.");
    m.line("#include <SDL3/SDL_main.h>");
    m.line();
    m.line("#include <cstdlib>");
    m.line("#include <cstring>");
    m.line("#include <iostream>");
    m.line("#include <string>");
    m.line();
    m.line("#include \"Project.hpp\"");
    m.line("#include \"scratch/Runtime.hpp\"");
    m.line();
    m.open("int main(int argc, char* argv[])");
    m.line("scratch::RuntimeConfig config = project::config();");
    m.line("// Optional command line overrides.");
    m.open("for (int i = 1; i < argc; ++i)");
    m.open("if (std::strcmp(argv[i], \"--scale\") == 0 && i + 1 < argc)");
    m.line("config.windowScale = std::atoi(argv[++i]);");
    m.dedent();
    m.line("} else if (std::strcmp(argv[i], \"--gpu\") == 0) {");
    m.indent();
    m.line("config.gpuAccel = true;   // optional Metal / Vulkan / D3D11 / threaded mesh renderer");
    m.dedent();
    m.line("} else if (std::strcmp(argv[i], \"--assets\") == 0 && i + 1 < argc) {");
    m.indent();
    m.line("config.assetsDir = std::string(argv[++i]) + \"/\";");
    m.dedent();
    m.line("} else if (std::strcmp(argv[i], \"--no-autostart\") == 0) {");
    m.indent();
    m.line("config.autoStart = false;");
    m.dedent();
    m.line("} else if (std::strcmp(argv[i], \"--frames\") == 0 && i + 1 < argc) {");
    m.indent();
    m.line("config.exitAfterFrames = std::atoi(argv[++i]);   // testing: quit after N frames");
    m.dedent();
    m.line("} else if (std::strcmp(argv[i], \"--screenshot\") == 0 && i + 1 < argc) {");
    m.indent();
    m.line("config.screenshotPath = argv[++i];               // testing: save last frame as BMP");
    m.dedent();
    m.line("} else if (std::strcmp(argv[i], \"--key-at\") == 0 && i + 1 < argc) {");
    m.indent();
    m.line("// testing: --key-at FRAME:KEY presses a Scratch key name at that frame");
    m.line("const std::string spec = argv[++i];");
    m.line("const size_t colon = spec.find(':');");
    m.open("if (colon != std::string::npos)");
    m.line("scratch::ScriptedInput in;");
    m.line("in.kind = scratch::ScriptedInput::Kind::KeyPress;");
    m.line("in.frame = std::atoi(spec.substr(0, colon).c_str());");
    m.line("in.key = spec.substr(colon + 1);");
    m.line("config.scriptedInputs.push_back(in);");
    m.close();
    m.dedent();
    m.line("} else if (std::strcmp(argv[i], \"--click-at\") == 0 && i + 1 < argc) {");
    m.indent();
    m.line("// testing: --click-at FRAME:X,Y clicks the stage at Scratch coordinates");
    m.line("const std::string spec = argv[++i];");
    m.line("const size_t colon = spec.find(':');");
    m.line("const size_t comma = spec.find(',');");
    m.open("if (colon != std::string::npos && comma != std::string::npos && comma > colon)");
    m.line("scratch::ScriptedInput in;");
    m.line("in.kind = scratch::ScriptedInput::Kind::Click;");
    m.line("in.frame = std::atoi(spec.substr(0, colon).c_str());");
    m.line("in.x = std::atof(spec.substr(colon + 1, comma - colon - 1).c_str());");
    m.line("in.y = std::atof(spec.substr(comma + 1).c_str());");
    m.line("config.scriptedInputs.push_back(in);");
    m.close();
    m.dedent();
    m.line("} else if (std::strcmp(argv[i], \"--help\") == 0) {");
    m.indent();
            m.line("std::cout << \"Usage: \" << argv[0] << \" [--scale N] [--gpu] [--assets DIR] [--no-autostart]\\n\"");
    m.line("          << \"       [--frames N] [--screenshot FILE.bmp] [--key-at FRAME:KEY] [--click-at FRAME:X,Y]\\n\";");
    m.line("return 0;");
    m.close();
    m.close();
    m.line();
    m.line("scratch::Runtime runtime(config);");
    m.line("project::registerTargets(runtime);");
    m.line("return runtime.run();");
    m.close();
    return m.str();
}

}  // namespace s2c::codegen
