#include "codegen/ReadmeGenerator.hpp"

namespace s2c::codegen {

std::string generateReadme(const ir::Project& project, const Diagnostics& diagnostics, const std::string& exe) {
    std::string md;
    md += "# " + project.title + "\n\n";
    md += "C++/SDL3 project generated by **scratch2cpp** from " + project.sourceDescription + ".\n\n";
    md += "The project is self-contained: it needs only CMake, a C++20 compiler and SDL3 "
          "(fetched automatically if not installed).\n\n";

    md += "## Build and run\n\n";
    md += "```sh\n";
    md += "cmake -S . -B build\n";
    md += "cmake --build build\n";
    md += "./build/" + exe + "          # Windows: build\\Release\\" + exe + ".exe\n";
    md += "```\n\n";
    md += "Or use the wrapper scripts:\n\n";
    md += "| Script | What it does |\n|---|---|\n";
    md += "| `scripts/build.sh [Release\\|Debug]` / `scripts\\build.bat` | configure + build into `build/` |\n";
    md += "| `scripts/run.sh` | build and launch |\n";
    md += "| `scripts/debug.sh` / `scripts\\debug.bat` | Debug build into `build/debug`, launched under lldb or gdb when available |\n\n";
    md += "Runtime options: `--scale N` (window size = stage size x N, default 2), "
          "`--gpu` (optional GPU / threaded mesh renderer; off by default; tries Metal, then Vulkan, "
          "then Direct3D 11, then a threaded CPU fallback), "
          "`--assets DIR`, `--no-autostart` (do not fire the green flag on launch).\n\n";

    md += "## Debugging\n\n";
    md += "`scripts/debug.sh` builds with `-DCMAKE_BUILD_TYPE=Debug` and runs `lldb -o run -- <exe>` "
          "(or `gdb -ex run --args <exe>`). Each Scratch script is a C++20 coroutine named "
          "`script_N` in `src/targets/<Sprite>.cpp`; set breakpoints there, e.g. "
          "`b Sprite_Player::script_1`. Custom blocks are `proc_<name>` member functions.\n\n";

    md += "## Layout\n\n";
    md += "```\n";
    md += "CMakeLists.txt      build configuration (finds or fetches SDL3)\n";
    md += "src/main.cpp        entry point\n";
    md += "src/Project.cpp     creates the stage and sprites in layer order\n";
    md += "src/targets/        one .cpp per Scratch sprite/stage: costumes, variables, scripts\n";
    md += "include/            matching headers\n";
    md += "runtime/            Scratch runtime library (scheduler, sprites, SDL3 rendering/input/audio)\n";
    md += "assets/             costumes and sounds (file names are the Scratch asset md5)\n";
    md += "scripts/            build/run/debug wrappers\n";
    md += "```\n\n";

    md += "## Targets\n\n";
    md += "| Target | Costumes | Sounds | Scripts | Variables | Lists |\n|---|---|---|---|---|---|\n";
    for (const ir::Target& t : project.targets) {
        md += "| " + (t.isStage ? std::string("Stage") : t.name) + " | " + std::to_string(t.costumes.size()) + " | " +
              std::to_string(t.sounds.size()) + " | " + std::to_string(t.scripts.size()) + " | " +
              std::to_string(t.variables.size()) + " | " + std::to_string(t.lists.size()) + " |\n";
    }
    md += "\n";

    md += "## Conversion notes\n\n";
    if (diagnostics.empty()) {
        md += "All blocks in this project were translated.\n";
    } else {
        md += "The converter reported the following. Unsupported blocks are kept as comments in the "
              "generated code and print a one-time notice when executed.\n\n";
        for (const Diagnostic& d : diagnostics.all()) md += "- " + d.message + "\n";
    }
    md += "\n";
    md += "Known limitations of the runtime: music, video and other non-pen extensions are not implemented; "
          "graphic effects other than ghost/brightness are ignored; sound is limited to WAV assets; "
          "speech bubbles, monitors and SVG costume text use a system TrueType font when one is available.\n";
    return md;
}

}  // namespace s2c::codegen
