// embed_files - build-time helper that turns files into C++ byte arrays.
//
// Usage: embed_files <output.cpp> <base-dir> <file>...
// Generates the table consumed by src/codegen/EmbeddedFiles.hpp so that the
// converter carries the runtime sources inside its own executable.
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

int main(int argc, char** argv) {
    if (argc < 3) {
        std::cerr << "usage: embed_files <output.cpp> <base-dir> <file>...\n";
        return 1;
    }
    const std::filesystem::path output = argv[1];
    const std::filesystem::path base = argv[2];

    std::ofstream out(output, std::ios::binary);
    if (!out) {
        std::cerr << "cannot write " << output << "\n";
        return 1;
    }
    out << "// Generated by tools/embed_files.cpp - do not edit.\n";
    out << "#include \"codegen/EmbeddedFiles.hpp\"\n\n";
    out << "namespace s2c::embedded {\nnamespace {\n";

    std::vector<std::pair<std::string, std::string>> entries;   // relative path, symbol
    for (int i = 3; i < argc; ++i) {
        const std::filesystem::path file = argv[i];
        std::ifstream in(file, std::ios::binary);
        if (!in) {
            std::cerr << "cannot read " << file << "\n";
            return 1;
        }
        std::vector<unsigned char> bytes((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
        std::string rel = std::filesystem::relative(file, base).generic_string();
        const std::string symbol = "kFile" + std::to_string(i - 3);
        out << "// " << rel << "\n";
        out << "const unsigned char " << symbol << "[] = {";
        for (size_t k = 0; k < bytes.size(); ++k) {
            if (k % 24 == 0) out << "\n   ";
            char buf[8];
            std::snprintf(buf, sizeof(buf), " 0x%02x,", bytes[k]);
            out << buf;
        }
        if (bytes.empty()) out << " 0x00";
        out << "\n};\n";
        out << "const std::size_t " << symbol << "Size = " << bytes.size() << ";\n\n";
        entries.emplace_back(rel, symbol);
    }

    out << "}  // namespace\n\n";
    out << "const std::vector<File>& runtimeFiles() {\n";
    out << "    static const std::vector<File> files = {\n";
    for (const auto& [rel, symbol] : entries) {
        out << "        {\"" << rel << "\", " << symbol << ", " << symbol << "Size},\n";
    }
    out << "    };\n    return files;\n}\n\n}  // namespace s2c::embedded\n";
    return 0;
}
